{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.stores .Values.externalSecrets.users }}
{{- $root := . }}
{{- range $user := .Values.externalSecrets.users }}
{{- $storeName := default "default" $user.store }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snowflake-user-{{ $user.username | replace "_" "-" }}
  labels:
    app.kubernetes.io/name: {{ $root.Values.app.name }}
    app.kubernetes.io/version: {{ $root.Release.Name }}-{{ $root.Release.Revision }}
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: {{ $root.Values.app.name }}-aws-secretstore-{{ $storeName }}
    kind: SecretStore
  target:
    name: snowflake-user-{{ $user.username | replace "_" "-" }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        private_key: "{{ `{{ .private_key }}` }}"
        {{- if $user.passphraseProperty }}
        passphrase: "{{ `{{ .passphrase }}` }}"
        {{- end }}
  data:
    - secretKey: private_key
      remoteRef:
        key: {{ $user.secretKey }}
        property: {{ $user.privateKeyProperty }}
    {{- with $user.passphraseProperty }}
    - secretKey: passphrase
      remoteRef:
        key: {{ $user.secretKey }}
        property: {{ . }}
    {{- end }}
{{- end }}
{{- end }}
