{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.stores }}
{{- $root := . }}
{{- range $name, $store := .Values.externalSecrets.stores }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ $root.Values.app.name }}-aws-secretstore-{{ $name }}
  labels:
    app.kubernetes.io/name: {{ $root.Values.app.name }}
    app.kubernetes.io/version: {{ $root.Release.Name }}-{{ $root.Release.Revision }}
spec:
  provider:
    aws:
      {{- if eq $store.type "secretsmanager" }}
      service: SecretsManager
      {{- else if eq $store.type "parameterstore" }}
      service: ParameterStore
      {{- end }}
      region: {{ required "Must set region!" $store.region }}
      {{- with $store.roleArn }}
      role: {{ . }}
      {{- end }}
      {{- with $store.externalID }}
      externalID: {{ . }}
      {{- end }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ $root.Values.serviceAccount.serviceAccountName | default "default" }}
---
{{- end }}
{{- end }}
